<a href="https://colab.research.google.com/github/qee20/productsentiment/blob/main/workinotebook/bertmodelfinetuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import os
from getpass import getpass

os.environ["GITHUB_USERNAME"] = input("GitHub username: ")
os.environ["GITHUB_TOKEN"] = getpass("GitHub token: ")

!git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/qee20/productsentiment.git

GitHub username: qee20
GitHub token: ··········
Cloning into 'productsentiment'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 42 (delta 11), reused 32 (delta 5), pack-reused 0 (from 0)
Receiving objects: 100% (42/42), 730.19 KiB | 3.13 MiB/s, done.
Resolving deltas: 100% (11/11), done.

Importing Datasets

In [9]:
import pandas as pd
ytcomment_df = pd.read_csv("/content/productsentiment/datasets/cleanedytcomment.csv")
ytcomment_df.head()

                                       clean_comment
0                 mau nanya ini ada ia camera nya ga
1               solusi buat ngatasin iklan di hp ini
2  hp kampret ini mah nyesel beli setiap updateny...
3                 bang ada stabilizer nya buat rekam
4  tentu ada kalo mau lebih stabil pake gimbal st...

Importing Trained Data

In [1]:
!git clone https://github.com/IndoNLP/indonlu.git

Cloning into 'indonlu'...
remote: Enumerating objects: 509, done.
remote: Counting objects: 100% (193/193), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 509 (delta 119), reused 139 (delta 110), pack-reused 316 (from 1)
Receiving objects: 100% (509/509), 9.46 MiB | 13.62 MiB/s, done.
Resolving deltas: 100% (239/239), done.

EDA

In [2]:
import pandas as pd

train_df = pd.read_csv('/content/indonlu/dataset/smsa_doc-sentiment-prosa/train_preprocess.tsv', sep='\t', header=None, names=['text', 'label'])
valid_df = pd.read_csv('/content/indonlu/dataset/smsa_doc-sentiment-prosa/valid_preprocess.tsv', sep='\t', header=None, names=['text', 'label'])

Install Necessary Libs

In [3]:
# 1. Install the latest version instead of 3.5.1
# !pip install transformers torch

from transformers import AutoTokenizer, AutoModelForSequenceClassification

# 2. Use the correct model class for classification
model_name = "indolem/indobert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)

# num_labels=3 implies categories like: [Positive, Neutral, Negative]
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=3)

print("Model loaded successfully with a classification head!")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/445M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at indolem/indobert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Model loaded successfully with a classification head!

Tokenizing Datasets

In [10]:

# Kita ubah jadi angka agar BERT paham
label_dict = {'positive': 2, 'neutral': 1, 'negative': 0}
train_df['label'] = train_df['label'].replace(label_dict)
valid_df['label'] = valid_df['label'].replace(label_dict)

# Proses Tokenizing
def tokenize_data(texts):
    return tokenizer(
        list(texts),
        padding='max_length',
        truncation=True,
        max_length=128,
        return_tensors='pt'
    )

# Tokenisasi data train dan valid
train_tokenized = tokenize_data(train_df['text'])
valid_tokenized = tokenize_data(valid_df['text'])

print("Tokenisasi selesai!")
print(f"Jumlah data train: {len(train_tokenized['input_ids'])}")

TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]

Dataset Class

In [5]:
import torch
from torch.utils.data import Dataset

class SmSADataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

# Bungkus data yang sudah di-tokenize tadi (dari tahap sebelumnya)
train_dataset = SmSADataset(train_tokenized, train_df['label'].values)
valid_dataset = SmSADataset(valid_tokenized, valid_df['label'].values)

print("Wadah data siap digunakan!")

Wadah data siap digunakan!

TrainingArguments

In [6]:
from transformers import TrainingArguments, Trainer, DataCollatorWithPadding

# Tentukan argumen training
training_args = TrainingArguments(
    output_dir='/content/training_results',          # Folder untuk menyimpan checkpoint
    num_train_epochs=3,              # Berapa kali model melihat seluruh data (3-5 biasanya cukup)
    per_device_train_batch_size=16,  # Jumlah data yang diproses sekaligus (sesuaikan dengan RAM GPU)
    per_device_eval_batch_size=16,
    warmup_steps=500,                # Penyesuaian bertahap di awal latihan
    weight_decay=0.01,               # Mencegah model menghafal (overfitting)
    logging_dir='/content/logs',            # Folder log
    logging_steps=100,               # Munculkan laporan setiap 100 langkah
    eval_strategy='steps',     # Evaluasi berkala agar kita tahu kemajuan model
    eval_steps=500,
    save_total_limit=1,              # Simpan hanya model terbaik saja agar tidak penuh
    load_best_model_at_end=True,     # Ambil versi model yang paling akurat di akhir
)

Training Process

In [7]:
# Inisialisasi Trainer
trainer = Trainer(
    model=model,                         # Model IndoBERT yang kita muat di awal
    args=training_args,                  # Aturan yang baru saja kita buat
    train_dataset=train_dataset,         # Wadah data train (11.000 baris)
    eval_dataset=valid_dataset,          # Wadah data validasi
)

# Mulai Training
print("Memulai proses training... Silakan tunggu.")
trainer.train()

Memulai proses training... Silakan tunggu.

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

 3

wandb: You chose "Don't visualize my results"

/tmp/ipython-input-1118073658.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}

/tmp/ipython-input-1118073658.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
/tmp/ipython-input-1118073658.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
/tmp/ipython-input-1118073658.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
/tmp/ipython-input-1118073658.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}

TrainOutput(global_step=2064, training_loss=0.2461547708326532, metrics={'train_runtime': 782.1427, 'train_samples_per_second': 42.192, 'train_steps_per_second': 2.639, 'total_flos': 2170685696256000.0, 'train_loss': 0.2461547708326532, 'epoch': 3.0})

Saving Model

In [11]:
model.save_pretrained("model_sentimen_akhir")
tokenizer.save_pretrained("model_sentimen_akhir")
print("Model sudah aman di folder 'model_sentimen_akhir'")

Model sudah aman di folder 'model_sentimen_akhir'

Apply to new data

In [12]:
def labeli_otomatis(text):
    # 1. Tokenisasi teks (mengubah teks jadi angka)
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=128).to("cuda")

    # 2. Prediksi menggunakan model yang sudah dilatih
    with torch.no_grad():
        outputs = model(**inputs)

    # 3. Ambil hasil tertinggi
    label_idx = torch.argmax(outputs.logits, dim=-1).item()

    # 4. Kembalikan dalam bentuk teks (sesuai mappingmu: 0=neg, 1=net, 2=pos)
    label_map = {0: 'Negative', 1: 'Neutral', 2: 'Positive'}
    return label_map[label_idx]

# --- PENERAPAN PADA DATASET ---
# Misal nama dataframe datamu adalah 'df_bersih'
# dan kolom teksnya adalah 'clean_comment'

ytcomment_df['clean_comment'] = ytcomment_df['clean_comment'].apply(labeli_otomatis)

# Cek hasil
print(ytcomment_df.head())

ValueError: text input must be of type `str` (single example), `list[str]` (batch or single pretokenized example) or `list[list[str]]` (batch of pretokenized examples).

In [13]:
# 1. Pastikan semua data adalah string dan tangani nilai kosong (NaN)
ytcomment_df['clean_comment'] = ytcomment_df['clean_comment'].astype(str).fillna('')

# 2. Hapus baris yang benar-benar kosong atau hanya spasi (opsional tapi disarankan)
ytcomment_df = ytcomment_df[ytcomment_df['clean_comment'].str.strip() != '']

# 3. Jalankan kembali prediksi
ytcomment_df['label_sentimen'] = ytcomment_df['clean_comment'].apply(labeli_otomatis)

print("Berhasil! Berikut hasilnya:")
print(ytcomment_df.head())

Berhasil! Berikut hasilnya:
                                       clean_comment label_sentimen
0                 mau nanya ini ada ia camera nya ga       Negative
1               solusi buat ngatasin iklan di hp ini        Neutral
2  hp kampret ini mah nyesel beli setiap updateny...       Negative
3                 bang ada stabilizer nya buat rekam       Positive
4  tentu ada kalo mau lebih stabil pake gimbal st...        Neutral